name: batching_future
version: 0.0.1
description: >-
  Batches multiple requests into a single batch requests which triggers once the maximum wait time or the maximum batch size is reached.
author: Jack Reilly <jackdreilly@gmail.com>
homepage: https://github.com/jackdreilly/batching_future
documentation: https://github.com/jackdreilly/batching_future
environment:
dependencies:
  quiver:
  synchronized:
dev_dependencies:
  test:
